---
label: Project
hide_body: false
fields:
- type: file
  name: featured_image
  config:
    maxSize: '1'
  label: Featured Image
- name: background_image
  type: file
  config:
    maxSize: 250
  label: Background Image
- type: color
  name: bg_color
  config:
    color_format: Hex
  label: Background color
- name: text_1
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Text 1
