---
label: Home
hide_body: true
fields:
- type: file
  name: featured_image
  config:
    maxSize: '1'
  label: Featured Image
- name: background_image
  type: file
  config:
    maxSize: 250
  label: Background Image
- type: color
  name: bg_color
  config:
    color_format: Hex
  label: Background color
- name: text_1
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Text 1
- name: text_2
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Text 2
- name: text_3
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Text 3
- name: text_4
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: true
    schema:
      format: html-blocks
  label: Text 4
- name: text_1_color
  type: color
  label: Text 1 Color
  config:
    required: false
    color_format: Hex
- name: text_2_color
  type: color
  label: Text 2 Color
  config:
    required: false
    color_format: Hex
- name: text_3_color
  type: color
  label: Text 3 Color
  config:
    required: false
    color_format: Hex
- name: text_4_color
  type: color
  label: Text 4 Color
  config:
    required: false
    color_format: Hex
